# name: CI
# on: ['push']

# jobs:
#   build:
#     runs-on: 'ubuntu-latest'
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v3
      
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
      
#       - name: Check out cargo code
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable

#       - name: Set up Docker Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v2
#         with:
#           driver: docker-container

#       - name: 'install brane with cargo'
#         uses: actions-rs/cargo@v1
#         with:
#           command: install
#           args: --git https://github.com/epi-project/brane brane-cli

#       - name: 'test the brane package'
#         run: |
#           brane build container.yml
